apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-topolvm.yaml
patches:
  - path: topolvm_mutatingwebhook_patch.yaml
  - path: topolvm_service_patch.yaml
  - path: topolvm_configmap-lvmd_patch.yaml
