name: builders
# Presubmit build and deploy from sources tests

on:
  pull_request:

jobs:
  centos9-bootc:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: quay.io/centos-bootc/centos-bootc
          bootc-image-tag: stream9
          build: bootc-image
          node-count: 2

  centos10-bootc:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: quay.io/centos-bootc/centos-bootc
          bootc-image-tag: stream10
          build: bootc-image
          node-count: 2

  fedora-bootc:
    strategy:
      matrix:
        runners: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          bootc-image-url: registry.fedoraproject.org/fedora-bootc
          bootc-image-tag: 42
          build: bootc-image
          node-count: 2

  ubuntu-rpm2deb:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build-deb
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}

  isolated-network:
    strategy:
      matrix:
        include:
          - name: kindnet
            runner: ubuntu-24.04
            ovnk-networking: 0
          - name: ovnk
            runner: ubuntu-24.04
            ovnk-networking: 1
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-branch: main
          okd-version-tag: ${{ steps.detect-okd-version.outputs.okd-version-tag }}
          isolated-network: 1
          ovnk-networking: ${{ matrix.ovnk-networking }}
          build: bootc-image
