name: installers
# Presubmit prebuilt packages tests.

on:
  pull_request:

jobs:
  quick-start-and-clean:
    if: ${{ !github.event.pull_request.draft }}
    strategy:
      matrix:
        runners: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runners }}
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      # Test the quick start and clean procedures with the latest published build
      # of the MicroShift container image.
      - name: Run the quick start script and clean scripts
        uses: ./.github/actions/quick-start-clean
